# Generated by Django 5.2.4 on 2025-08-11 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20250809_0401'),
        ('supply_chain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseorderitem',
            name='chk_po_item_positive_values',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseorderitem',
            name='chk_po_item_received_not_exceed_ordered',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='received_quantity',
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_quantity__gt', 0), ('unit_price_at_order__gt', 0)), name='chk_po_item_positive_values'),
        ),
    ]
