# Generated by Django 5.2.6 on 2025-12-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_alter_payment_amount_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['company_name']},
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='firstname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='mobile',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='salutation',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='work_phone',
        ),
    ]
