# Generated by Django 5.2.6 on 2025-12-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
