# Generated by Django 5.2.4 on 2025-08-15 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_rename_expected_delivery_date_purchaseorder_delivery_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseorder',
            name='chk_po_delivery_date',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseorderitem',
            name='chk_po_item_positive_values',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_date__gte', models.F('order_date'))), name='chk_po_delivery_date'),
        ),
    ]
