# Generated by Django 5.2.4 on 2025-08-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0005_alter_purchaseorder_delivery_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='purchaseorder',
            name='chk_po_total_amount',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseorder',
            name='chk_po_delivery_date',
        ),
        migrations.RenameField(
            model_name='goodsreceipt',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='goodsreceiptitem',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='supplierpayment',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
