# Generated by Django 5.2.6 on 2025-12-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0006_alter_supplier_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='idd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
