# Generated by Django 5.2.6 on 2025-12-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0007_purchaseorder_idd'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='idd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='idd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='idd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='idd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
