# Generated by Django 5.2.4 on 2025-08-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0007_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_amount',
        ),
    ]
