# Generated by Django 5.2.6 on 2025-12-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0008_goodsreceipt_idd_goodsreceiptitem_idd_payment_idd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='idd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
