# Generated by Django 5.2.6 on 2025-12-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0009_supplier_idd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='idd',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptitem',
            name='idd',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='idd',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='idd',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='idd',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='idd',
        ),
    ]
