# Generated by Django 5.2.4 on 2025-08-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0009_alter_goodsreceipt_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['firstname']},
        ),
        migrations.RemoveConstraint(
            model_name='goodsreceiptitem',
            name='chk_receipt_item_positive_quantity',
        ),
        migrations.RemoveConstraint(
            model_name='supplierpayment',
            name='chk_positive_payment_amount',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='salutation',
            field=models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('miss', 'Miss'), ('ms', 'Ms.'), ('dr', 'Dr.'), ('prof', 'Prof.')], default='mr', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='work_phone',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
