# Generated by Django 6.0.4 on 2026-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0010_remove_goodsreceipt_idd_remove_goodsreceiptitem_idd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer')], default='transfer', max_length=20),
        ),
    ]
