# Generated by Django 6.0.4 on 2026-06-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0012_alter_supplier_address_alter_supplier_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsreceiptitem',
            options={'ordering': ['created_at']},
        ),
    ]
