# Generated by Django 5.2.4 on 2025-08-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0014_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
    ]
