# Generated by Django 5.2.4 on 2025-08-24 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0015_alter_payment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceiptitem',
            name='actual_product',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptitem',
            name='serial_item',
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 24, 5, 51, 21, 548651, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 24, 5, 51, 21, 547756, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 24, 5, 51, 21, 546007, tzinfo=datetime.timezone.utc)),
        ),
    ]
