# Generated by Django 5.2.4 on 2025-08-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0017_alter_goodsreceipt_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceipt',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('voided', 'Voided')], default='received', max_length=20),
        ),
    ]
