# Generated by Django 5.2.4 on 2025-08-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0018_alter_goodsreceipt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='gr_number',
            field=models.CharField(default=0, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
