# Generated by Django 5.2.4 on 2025-08-28 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_product_options'),
        ('supply_chain', '0019_goodsreceipt_gr_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsreceipt',
            options={'ordering': ['-created_by']},
        ),
        migrations.AlterField(
            model_name='goodsreceiptitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='inventory.product'),
        ),
    ]
