# Generated by Django 5.2.6 on 2025-11-12 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customer', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseagreeemntlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_agreement_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='purchaseagreeemntlineitem',
            name='purchase_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_line_items', to='customer.purchaseagreeemnt'),
        ),
        migrations.AddField(
            model_name='purchaseagreeemntlineitem',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='customer.purchaseagreeemntlineitem'),
        ),
        migrations.AddField(
            model_name='purchaseagreeemntlineitem',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasefulfillment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasefulfillment',
            name='purchase_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_fulfillments', to='customer.purchaseagreeemnt'),
        ),
        migrations.AddField(
            model_name='purchasefulfillment',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasefulfillmentlineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasefulfillmentlineitem',
            name='fullfilment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fullfilment_items', to='customer.purchasefulfillment'),
        ),
        migrations.AddField(
            model_name='purchasefulfillmentlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fullfilment_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='purchasefulfillmentlineitem',
            name='purchase_agreement_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fullfilment_items', to='customer.purchaseagreeemntlineitem'),
        ),
        migrations.AddField(
            model_name='purchasefulfillmentlineitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='customer.depositaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_number'], name='customer_cu_custome_d3a0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customer_cu_phone_1af1fe_idx'),
        ),
        migrations.AddIndex(
            model_name='depositaccount',
            index=models.Index(fields=['account_number'], name='customer_de_account_c5fff8_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseagreeemntlineitem',
            constraint=models.UniqueConstraint(fields=('purchase_agreement', 'line_number', 'version'), name='unique_line_version'),
        ),
    ]
