# Generated by Django 5.2.6 on 2025-11-15 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseAgreeemnt',
            new_name='PurchaseAgreement',
        ),
        migrations.RenameModel(
            old_name='PurchaseAgreeemntLineItem',
            new_name='PurchaseAgreementLineItem',
        ),
        migrations.AddField(
            model_name='cfafulfillment',
            name='naira_settled',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('voided', 'Voided')], default='active', max_length=20),
        ),
    ]
