# Generated by Django 5.2.6 on 2025-11-16 01:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_purchaseagreeemnt_purchaseagreement_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cfafulfillment',
            old_name='fulfilment_number',
            new_name='fulfillment_number',
        ),
        migrations.RenameField(
            model_name='purchasefulfillment',
            old_name='fulfilment_number',
            new_name='fulfillment_number',
        ),
        migrations.RenameField(
            model_name='purchasefulfillmentlineitem',
            old_name='fullfilment_item_id',
            new_name='fulfillment_item_id',
        ),
        migrations.RenameField(
            model_name='purchasefulfillmentlineitem',
            old_name='fulfilment_item_number',
            new_name='fulfillment_item_number',
        ),
        migrations.RemoveField(
            model_name='purchasefulfillmentlineitem',
            name='fullfilment',
        ),
        migrations.AddField(
            model_name='purchasefulfillmentlineitem',
            name='fulfillment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_items', to='customer.purchasefulfillment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cfafulfillment',
            name='fulfillment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchasefulfillmentlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_items', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='purchasefulfillmentlineitem',
            name='purchase_agreement_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_items', to='customer.purchaseagreementlineitem'),
        ),
    ]
