# Generated by Django 5.2.6 on 2025-11-16 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customer', '0004_rename_fulfilment_number_cfafulfillment_fulfillment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
