# Generated by Django 5.2.6 on 2025-11-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_transaction_source_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
