# Generated by Django 5.2.6 on 2025-11-16 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_transaction_source_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseagreement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaseagreementlineitem',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
