# Generated by Django 5.2.6 on 2025-11-20 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_purchaseagreement_date_and_more'),
        ('inventory', '0002_remove_saleitem_sale_remove_saleitem_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasefulfillmentlineitem',
            name='fulfillment',
        ),
        migrations.RemoveField(
            model_name='purchasefulfillmentlineitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchasefulfillmentlineitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasefulfillmentlineitem',
            name='purchase_agreement_item',
        ),
        migrations.RemoveField(
            model_name='purchasefulfillmentlineitem',
            name='updated_by',
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('payment_method', models.CharField(choices=[('bank transfer', 'Bank Transfer'), ('cash', 'Cash'), ('from deposit', 'From Deposit')], default='bank transfer', max_length=50)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('voided', 'Voided')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_sales', to='customer.purchaseagreement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_sales', to='customer.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoupledSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupled_sale_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupled_sales', to='customer.purchaseagreementlineitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupled_sales', to=settings.AUTH_USER_MODEL)),
                ('transformation_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupled_sales', to='inventory.transformationitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_coupled_sales', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupled_sales', to='customer.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoxedSale',
            fields=[
                ('boxed_sale_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boxed_sale_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxed_sales', to='customer.purchaseagreementlineitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boxed_sales', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxed_sales', to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_boxed_sales', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxed_sales', to='customer.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PurchaseFulfillment',
        ),
        migrations.DeleteModel(
            name='PurchaseFulfillmentLineItem',
        ),
        migrations.AddConstraint(
            model_name='coupledsale',
            constraint=models.UniqueConstraint(fields=('transformation_item',), name='unique_transformation_item_per_coupled_sale'),
        ),
    ]
