# Generated by Django 5.2.6 on 2025-11-20 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_purchasefulfillmentlineitem_fulfillment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupledsale',
            name='id',
        ),
        migrations.AddField(
            model_name='coupledsale',
            name='coupled_sale_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
