# Generated by Django 5.2.6 on 2025-11-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_cfaagreement_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('fulfillment', 'Fulfillment'), ('refund', 'Refund')], max_length=30),
        ),
    ]
