# Generated by Django 5.2.6 on 2025-11-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_remove_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfafulfillment',
            name='naira_settled',
        ),
    ]
