# Generated by Django 5.2.6 on 2025-11-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_cfafulfillment_naira_settled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxedsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxed_sales', to='customer.sale'),
        ),
        migrations.AlterField(
            model_name='coupledsale',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_sales', to='customer.purchaseagreement'),
        ),
    ]
