# Generated by Django 5.2.6 on 2025-11-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_boxedsale_sale_alter_coupledsale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxedsale',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
