# Generated by Django 5.2.6 on 2025-11-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_boxedsale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseagreementlineitem',
            name='quantity_ordered',
            field=models.IntegerField(),
        ),
    ]
