# Generated by Django 5.2.6 on 2025-12-02 04:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_purchaseagreementlineitem_quantity_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfafulfillment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
