# Generated by Django 5.2.6 on 2025-12-02 05:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_cfafulfillment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfaagreement',
            name='amount_allocated',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'))]),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Naira per XOF 1,000', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'))]),
        ),
    ]
