# Generated by Django 5.2.6 on 2025-12-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_cfaagreement_amount_allocated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfafulfillment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('VOIDED', 'Voided')], default='ACTIVE', max_length=20),
        ),
    ]
