# Generated by Django 5.2.6 on 2025-12-05 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_cfafulfillment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxedsale',
            name='agreement_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boxed_sales', to='customer.purchaseagreementlineitem'),
        ),
    ]
