# Generated by Django 5.2.6 on 2025-12-05 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_alter_boxedsale_agreement_line_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupledsale',
            name='agreement_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupled_sales', to='customer.purchaseagreementlineitem'),
        ),
    ]
