# Generated by Django 5.2.6 on 2025-12-07 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_alter_coupledsale_agreement_line_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='agreement',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('status__in', ['FULFILLED', 'CANCELLED']), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_sales', to='customer.purchaseagreement'),
        ),
    ]
