# Generated by Django 5.2.6 on 2025-12-07 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_alter_sale_agreement'),
        ('inventory', '0002_remove_saleitem_sale_remove_saleitem_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxedsale',
            name='agreement_line_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('status__in', ['FULFILLED', 'VOIDED']), _negated=True), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boxed_sales', to='customer.purchaseagreementlineitem'),
        ),
        migrations.AlterField(
            model_name='boxedsale',
            name='product',
            field=models.ForeignKey(limit_choices_to=models.Q(('type_variant', 'boxed')), on_delete=django.db.models.deletion.PROTECT, related_name='boxed_sales', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='coupledsale',
            name='agreement_line_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('status__in', ['FULFILLED', 'VOIDED']), _negated=True), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupled_sales', to='customer.purchaseagreementlineitem'),
        ),
        migrations.AlterField(
            model_name='coupledsale',
            name='transformation_item',
            field=models.ForeignKey(limit_choices_to=models.Q(('status', 'sold'), _negated=True), on_delete=django.db.models.deletion.PROTECT, related_name='coupled_sales', to='inventory.transformationitem'),
        ),
    ]
