# Generated by Django 5.2.6 on 2025-12-07 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_alter_boxedsale_agreement_line_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxedsale',
            name='agreement_line_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('status__in', ['FULFILLED', 'VOIDED', 'CANCELLED']), _negated=True), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boxed_sales', to='customer.purchaseagreementlineitem'),
        ),
        migrations.AlterField(
            model_name='coupledsale',
            name='agreement_line_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('status__in', ['FULFILLED', 'VOIDED', 'CANCELLED']), _negated=True), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupled_sales', to='customer.purchaseagreementlineitem'),
        ),
        migrations.AlterField(
            model_name='purchaseagreementlineitem',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('VOIDED', 'Voided'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=30),
        ),
    ]
