# Generated by Django 5.2.6 on 2025-12-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='idd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='idd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
