# Generated by Django 5.2.6 on 2025-12-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_alter_customer_options_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
