# Generated by Django 5.2.6 on 2025-12-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_alter_sale_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='idd',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='idd',
        ),
    ]
