# Generated by Django 5.2.6 on 2026-02-03 03:45

from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0032_remove_customer_idd_remove_transaction_idd"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositaccount",
            name="cached_total_balance",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                null=True,
                blank=True,
                db_index=True,
                help_text="Cached total balance for performance",
            ),
        ),
        migrations.AddField(
            model_name="depositaccount",
            name="cached_allocated_balance",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                null=True,
                blank=True,
                db_index=True,
                help_text="Cached allocated balance for performance",
            ),
        ),
        migrations.AddField(
            model_name="depositaccount",
            name="cached_available_balance",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                null=True,
                blank=True,
                db_index=True,
                help_text="Cached available balance for performance",
            ),
        ),
        migrations.AddField(
            model_name="depositaccount",
            name="balances_last_updated",
            field=models.DateTimeField(
                null=True, blank=True, help_text="When balances were last recalculated"
            ),
        ),
    ]
