# Generated by Django 5.2.6 on 2026-04-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_add_cached_balances'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sale',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
    ]
