# Generated by Django 6.0.4 on 2026-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_alter_customer_options_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxedsale',
            name='cost_basis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total FIFO cost of units sold at sale time', max_digits=15, null=True),
        ),
    ]
