# Generated by Django 6.0.4 on 2026-05-14 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_boxedsale_cost_basis'),
        ('inventory', '0008_transformationitem_consumed_layer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxedSaleLayerConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_consumed', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boxed_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_consumptions', to='customer.boxedsale')),
                ('cost_layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_consumptions', to='inventory.inventorycostlayer')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['boxed_sale'], name='customer_bo_boxed_s_6b2017_idx'), models.Index(fields=['cost_layer'], name='customer_bo_cost_la_99d8a6_idx')],
            },
        ),
    ]
