# Generated by Django 6.0.4 on 2026-06-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_boxedsalelayerconsumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseagreementlineitem',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
    ]
