# Generated by Django 6.0.4 on 2026-06-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='depositaccount',
            options={'ordering': ['account_number']},
        ),
    ]
