# Generated by Django 5.2.4 on 2025-08-04 19:16

import django.db.models.deletion
import loan.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(choices=[('sales loan', 'Sales Loan'), ('normal loan', 'Normal Loan')], max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('written off', 'Written Off'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_loans', to='customer.customer')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_sales', to='customer.sale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayments',
            fields=[
                ('repayment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repayment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer')], default='cash', max_length=20)),
                ('trxn_ref', models.CharField(default=loan.models.LoanRepayments.generate_txn_ref, editable=False, max_length=50, unique=True)),
                ('remark', models.TextField(blank=True, default='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayments', to='loan.loan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('loan_type', 'sales loan'), ('sale_id__isnull', False)), models.Q(('loan_type', 'normal loan'), ('sale_id__isnull', True)), _connector='OR'), name='chk_loan_type_sale_logic'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('principal_amount__gt', 0)), name='chk_positive_principal_amount'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('loan_date'))), name='chk_due_date_logic'),
        ),
        migrations.AddConstraint(
            model_name='loanrepayments',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_positive_repayment_amount'),
        ),
    ]
