# Generated by Django 6.0.4 on 2026-06-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-loan_date']},
        ),
        migrations.AlterModelOptions(
            name='loanrepayments',
            options={'ordering': ['-repayment_date'], 'verbose_name_plural': 'Loan Repayments'},
        ),
    ]
