# Generated by Django 5.2.4 on 2025-08-04 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('modelname', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('engine', 'Engine')], max_length=20)),
                ('type_variant', models.CharField(choices=[('boxed', 'Boxed'), ('coupled', 'Coupled'), ('spare part', 'Spare Part')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('base_product', models.ForeignKey(blank=True, help_text='Parent product if this is a variant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='inventory.product')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='inventory.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransformation',
            fields=[
                ('transformation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine_number', models.CharField(max_length=255, unique=True)),
                ('chassis_number', models.CharField(max_length=255, unique=True)),
                ('transformation_date', models.DateTimeField(auto_now_add=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('boxed_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxed_products', to='inventory.product')),
                ('coupled_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupled_products', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.IntegerField()),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='SerializedInventory',
            fields=[
                ('serial_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine_number', models.CharField(max_length=255, unique=True)),
                ('chassis_number', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('damaged', 'Damaged')], default='available', max_length=20)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_products', to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
