# Generated by Django 5.2.4 on 2025-08-07 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('base_product__isnull', False), ('type_variant', 'coupled')), name='chkBaseProduct'),
        ),
    ]
