# Generated by Django 5.2.4 on 2025-08-07 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_chkbaseproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='chkBaseProduct',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('base_product__isnull', False), ('type_variant', 'coupled')), models.Q(('base_product__isnull', True), ('type_variant', 'boxed')), _connector='OR'), name='chkBaseProduct'),
        ),
    ]
