# Generated by Django 5.2.6 on 2025-12-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_saleitem_sale_remove_saleitem_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='idd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='idd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
