# Generated by Django 5.2.6 on 2025-12-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_brand_idd_product_idd'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='idd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transformationitem',
            name='idd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
