# Generated by Django 5.2.6 on 2025-12-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_transformation_idd_transformationitem_idd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='idd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='idd',
        ),
        migrations.RemoveField(
            model_name='transformation',
            name='idd',
        ),
        migrations.RemoveField(
            model_name='transformationitem',
            name='idd',
        ),
    ]
