# Generated by Django 5.2.4 on 2025-08-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_brand_create_at_brand_created_by_brand_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='inventorytransformation',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='serializedinventory',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
