# Generated by Django 5.2.4 on 2025-08-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_create_at_brand_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('engine', 'Engine'), ('spare part', 'Spare Part')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_variant',
            field=models.CharField(choices=[('boxed', 'Boxed'), ('coupled', 'Coupled')], max_length=20),
        ),
    ]
