# Generated by Django 6.0.4 on 2026-05-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_brand_idd_remove_product_idd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='assembly_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
