# Generated by Django 5.2.4 on 2025-08-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_category_alter_product_type_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('engine', 'Engine'), ('spare part', 'Spare Part')], default='boxed', max_length=20),
        ),
    ]
