# Generated by Django 6.0.4 on 2026-05-13 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_assembly_cost'),
        ('supply_chain', '0011_alter_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCostLayer',
            fields=[
                ('cost_layer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goods_receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_layers', to='supply_chain.goodsreceiptitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='inventory.product')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='inventory_i_product_a6dfd3_idx'), models.Index(fields=['goods_receipt_item'], name='inventory_i_goods_r_492eea_idx')],
            },
        ),
    ]
