# Generated by Django 6.0.4 on 2026-05-14 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventorycostlayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformationitem',
            name='consumed_layer',
            field=models.ForeignKey(blank=True, help_text='The FIFO cost layer consumed during this transformation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformation_consumptions', to='inventory.inventorycostlayer'),
        ),
        migrations.AlterField(
            model_name='transformationitem',
            name='source_product',
            field=models.ForeignKey(limit_choices_to={'type_variant': 'boxed'}, on_delete=django.db.models.deletion.PROTECT, related_name='transform_from', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='transformationitem',
            name='target_product',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_variant': 'coupled'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transform_to', to='inventory.product'),
        ),
    ]
