# Generated by Django 6.0.4 on 2026-05-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_transformationitem_consumed_layer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycostlayer',
            name='is_voided',
            field=models.BooleanField(default=False, help_text='True when the receipt that created this layer has been voided'),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
