# Generated by Django 5.2.4 on 2025-08-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_base_product_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('engine', 'Engine'), ('spare part', 'Spare Part'), ('', 'Select a Category')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_variant',
            field=models.CharField(choices=[('boxed', 'Boxed'), ('coupled', 'Coupled'), ('', 'Select a Category')], default='', max_length=20),
        ),
    ]
