# Generated by Django 5.2.4 on 2025-08-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_product_category_alter_product_type_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_variant',
            field=models.CharField(choices=[('boxed', 'Boxed'), ('coupled', 'Coupled'), ('', 'Select a Type')], default='', max_length=20),
        ),
    ]
