# Generated by Django 6.0.4 on 2026-05-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventorycostlayer_is_voided_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformationitem',
            name='chassis_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transformationitem',
            name='engine_number',
            field=models.CharField(max_length=100),
        ),
    ]
