# Generated by Django 6.0.4 on 2026-06-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_transformationitem_chassis_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='transformation',
            options={'ordering': ['-transformation_date']},
        ),
        migrations.AlterModelOptions(
            name='transformationitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='transformationitem',
            name='chassis_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transformationitem',
            name='engine_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
