# Generated by Django 6.0.4 on 2026-06-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_add_unique_engine_chassis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-quantity'], 'verbose_name_plural': 'Inventories'},
        ),
    ]
