# Generated by Django 5.2 on 2025-08-09 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_options_alter_product_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='chkBaseProduct',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('base_product__isnull', False), ('type_variant', 'coupled')), models.Q(('base_product__isnull', True), ('type_variant', 'boxed')), _connector='OR'), name='Product have a parent if not boxed!'),
        ),
    ]
