# Generated by Django 5.2 on 2025-08-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_product_chkbaseproduct_and_more'),
    ]

    operations = [
    ]
