# Generated by Django 5.2 on 2025-08-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20250809_0241'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='Product have a parent if not boxed!',
        ),
    ]
