# Generated by Django 5.2 on 2025-08-09 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_product_is_active'),
    ]

    operations = [
    ]
