# Generated by Django 5.2.4 on 2025-08-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_brand_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['brand']},
        ),
    ]
