# Generated by Django 5.2.4 on 2025-08-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_variant',
            field=models.CharField(choices=[('boxed', 'Boxed'), ('coupled', 'Coupled'), ('', 'Select a Type')], default='boxed', max_length=20),
        ),
    ]
