# Generated by Django 5.2.4 on 2025-08-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_product_type_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('reserved', 'Reserved'), ('damaged', 'Damaged')], default='active', max_length=10),
        ),
    ]
