# Generated by Django 5.2.4 on 2025-09-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_product_is_active_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_on_hand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
